version: "3.9"
services:
  frontend:
    build: ./frontend
    environment:
      PORT: ${FRONTEND_PORT}
      REACT_APP_API_BASE_URL: "https://localhost/api"
    restart: always
    expose:
      - "${FRONTEND_PORT}"
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - backend
  
  backend:
    build: ./server
    environment:
      PORT: ${BACKEND_PORT}
      ATLAS_URI: mongodb://${APP_DB_USERNAME}:${APP_DB_PASSWORD}@mongo:27017/${APP_DB_NAME}?authSource=${APP_DB_NAME}
    restart: always
    expose:
      - "${BACKEND_PORT}"
    networks:
      - backend_net
      - db_net
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6
    restart: always
    command: --bind_ip_all --logpath /var/log/mongodb/mongod.log --logappend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${APP_DB_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
      - ./server/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - db_net
  
  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${ADMIN_USER}:${ADMIN_PASS}@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${ADMIN_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ADMIN_PASS}
    depends_on:
      - mongo
    expose:
      - "8081"
    networks:
      - backend_net
      - db_net
  
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - frontend_net
      - backend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge
  db_net:
    driver: bridge

volumes:
  mongo_data: