apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
        - name: mern-app
          image: mern-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
